// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'editor-container': string;
  'editor-resizer': string;
  'editor-wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
