// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'graph-container': string;
  'graph-layout': string;
  'graph-layout-scale': string;
  'graph-layout-stretch': string;
  'graph-toolbar': string;
  'graph-toolbar__layout': string;
  'graph-toolbar__layout_button': string;
  'graph-toolbar__layout_button-active': string;
  'graph-toolbar__theme-item': string;
  'graph-toolbar__theme-item-active': string;
  'graph-toolbar__theme-list': string;
  'guide-container': string;
  'guide__logo': string;
  'guide__text': string;
  'guide__title': string;
  'guide__version': string;
  'transition__fade-entered': string;
  'transition__fade-entering': string;
  'transition__fade-exited': string;
  'transition__fade-exiting': string;
}
export const cssExports: CssExports;
export default cssExports;
