// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'graph-container': string;
  'graph-toolbar': string;
  'graph-toolbar__theme-item': string;
  'graph-toolbar__theme-list': string;
  'graph-wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
